export const VACANCY_CREATE_REQUEST = "VACANCY_CREATE_REQUEST";
export const VACANCY_CREATE_SUCCESS = "VACANCY_CREATE_SUCCESS";
export const VACANCY_CREATE_FAILURE = "VACANCY_CREATE_FAILURE";

export const VACANCY_UPDATE_REQUEST = "VACANCY_UPDATE_REQUEST";
export const VACANCY_UPDATE_SUCCESS = "VACANCY_UPDATE_SUCCESS";
export const VACANCY_UPDATE_FAILURE = "VACANCY_UPDATE_FAILURE";

export const VACANCY_GET_ONE_REQUEST = "VACANCY_GET_ONE_REQUEST";
export const VACANCY_GET_ONE_SUCCESS = "VACANCY_GET_ONE_SUCCESS";
export const VACANCY_GET_ONE_FAILURE = "VACANCY_GET_ONE_FAILURE";

export const VACANCY_GET_ALL_REQUEST = "VACANCY_GET_ALL_REQUEST";
export const VACANCY_GET_ALL_SUCCESS = "VACANCY_GET_ALL_SUCCESS";
export const VACANCY_GET_ALL_FAILURE = "VACANCY_GET_ALL_FAILURE";

export const VACANCY_DELETE_ONE_REQUEST = "VACANCY_DELETE_ONE_REQUEST";
export const VACANCY_DELETE_ONE_SUCCESS = "VACANCY_DELETE_ONE_SUCCESS";
export const VACANCY_DELETE_ONE_FAILURE = "VACANCY_DELETE_ONE_FAILURE";

export const VACANCY_DELETE_ALL_REQUEST = "VACANCY_DELETE_ALL_REQUEST";
export const VACANCY_DELETE_ALL_SUCCESS = "VACANCY_DELETE_ALL_SUCCESS";
export const VACANCY_DELETE_ALL_FAILURE = "VACANCY_DELETE_ALL_FAILURE";
